"""use singular table names

Revision ID: 37352d51d4d5
Revises: c4d8e2f1a907
Create Date: 2026-08-29 17:28:36.583908

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "37352d51d4d5"
down_revision: Union[str, Sequence[str], None] = "c4d8e2f1a907"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookmarks_id"), table_name="bookmark")
    op.drop_index(op.f("ix_bookmarks_short_code"), table_name="bookmark")
    op.create_index(op.f("ix_bookmark_id"), "bookmark", ["id"], unique=False)
    op.create_index(
        op.f("ix_bookmark_short_code"), "bookmark", ["short_code"], unique=True
    )
    op.drop_index(op.f("ix_users_id"), table_name="user")
    op.drop_constraint(op.f("users_email_key"), "user", type_="unique")
    op.drop_constraint(op.f("users_username_key"), "user", type_="unique")
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_unique_constraint(op.f("uq_user_email"), "user", ["email"])
    op.create_unique_constraint(op.f("uq_user_username"), "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_username"), "user", type_="unique")
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.create_unique_constraint(
        op.f("users_username_key"),
        "user",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "user", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("ix_users_id"), "user", ["id"], unique=False)
    op.drop_index(op.f("ix_bookmark_short_code"), table_name="bookmark")
    op.drop_index(op.f("ix_bookmark_id"), table_name="bookmark")
    op.create_index(
        op.f("ix_bookmarks_short_code"), "bookmark", ["short_code"], unique=True
    )
    op.create_index(op.f("ix_bookmarks_id"), "bookmark", ["id"], unique=False)
    # ### end Alembic commands ###
