"""add visits model

Revision ID: 694a3133d0eb
Revises: 851417f6233c
Create Date: 2026-08-27 11:57:50.039075

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "694a3133d0eb"
down_revision: Union[str, Sequence[str], None] = "851417f6233c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
